language: python
python:
  - 2.7
  - 3.3
  - 3.4
install:
  - pip install -r requirements.txt -r test-requirements.txt
script:
  - nosetests --verbose --with-cov --cov-report xml --cover-package=sphinxcontrib.chapeldomain
after_success:
  - coveralls
