name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install tox

    - name: Lint
      run: |
        python3 -m tox -e flake8

    - name: Test
      run: |
        python3 -m tox -e py

    - name: Make docs
      run: |
        python3 -m tox -e docs,doc-test

    - name: Coverage
      run: |
        python3 -m tox -e coverage

    - name: Upload codecov
      uses: codecov/codecov-action@v2
