name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt -r test-requirements.txt -r docs-requirements.txt
    - name: Lint
      run: flake8 sphinxcontrib/
    - name: Test
      run: nosetests --verbose --with-cov --cov-report xml --cover-package=sphinxcontrib.chapeldomain
    - name: Make docs
      run: |
        ( export PYTHONPATH=`pwd` && cd docs/ && make html )
        ( export PYTHONPATH=`pwd` && cd doc-test/ && make html )
    - name: Codecode
      uses: codecov/codecov-action@v2
